version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQATESTgit210725Project
  gitServerName: Kusi_VCTest
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
services:
- serviceName: project.siqatestgit210725.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQATESTgit210725Project
    version: "1.0"
- serviceName: project.siqatestgit210725.integrations:SIQAAdapterFlow
  packages:
  - name: SIQATESTgit210725Project
    version: "1.0"
